# Generated by Django 3.1.7 on 2021-04-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_office_utilization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='utilization',
        ),
    ]
