# Generated by Django 3.1.7 on 2021-04-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_office_utilization'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='utilization',
            field=models.IntegerField(default=0),
        ),
    ]
